name: ContinuousDocumentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pdoc3
      run: pip install pdoc3

    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.3.0

    - name: Configure poetry
      shell: bash
      run: python -m poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        python -m poetry install

    - name: Generate documentation
      run: pdoc --html -o docs kgforge --force

    - name: Upload documentation to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs/kgforge

    - name: Deploy documentation to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        github-token: ${{ secrets.GH_TOKEN }}
